name: Telegram notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Pull Request Number (if available)
        id: pr
        run: echo "PR_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository }}:${{ github.ref }} | jq -r '.[0].number')" >> $GITHUB_ENV

      - name: Check if Pull Request Number is available
        id: check_pr
        run: echo "PR_AVAILABLE=$(if [ -z $PR_NUMBER ]; then echo 'false'; else echo 'true'; fi)" >> $GITHUB_ENV

      - name: Telegram Notify on New Pull Request
        if: env.PR_AVAILABLE == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            A new PR is raised [here](https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }})

      - name: Telegram Notify on Commit to Existing Pull Request
        if: env.PR_AVAILABLE == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            A new commit is added to [here](https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }})
